
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum NumericType
    {
        Max = 10000,

        /// <summary>
        /// 生命值
        /// </summary>
        Hp = 1000,

        /// <summary>
        /// 生命值Base
        /// </summary>
        HpBase = 10001,

        /// <summary>
        /// 最大生命值
        /// </summary>
        MaxHp = 1001,

        /// <summary>
        /// 最大生命值Base
        /// </summary>
        MaxHpBase = 10011,

        MaxHpAdd = 10012,

        MaxHpPct = 10013,

        MaxHpFinalAdd = 10014,

        MaxHpFinalPct = 10015,

        Speed = 1002,

        SpeedBase = 10021,

        SpeedAdd = 10022,

        SpeedPct = 10023,

        SpeedFinalAdd = 10024,

        SpeedFinalPct = 10025,

        AOI = 1003,

        AOIBase = 10031,

        AOIAdd = 10032,

        AOIPct = 10033,

        AOIFinalAdd = 10034,

        AOIFinalPct = 10035,

    }
}
