
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class UnitConfig : BeanBase
    {
        public UnitConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Type = _buf.ReadInt();
            Name = _buf.ReadString();
            Position = _buf.ReadInt();
            Height = _buf.ReadInt();
            Weight = _buf.ReadInt();
            AI = _buf.ReadInt();
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Numeric = new System.Collections.Generic.Dictionary<NumericType, long>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { NumericType _k0;  _k0 = (NumericType)_buf.ReadInt(); long _v0;  _v0 = _buf.ReadLong();     Numeric.Add(_k0, _v0);}}

            PostInit();
        }

        public static UnitConfig DeserializeUnitConfig(ByteBuf _buf)
        {
            return new UnitConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// Type
        /// </summary>
        public readonly int Type;

        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;

        /// <summary>
        /// 位置
        /// </summary>
        public readonly int Position;

        /// <summary>
        /// 身高
        /// </summary>
        public readonly int Height;

        /// <summary>
        /// 体重
        /// </summary>
        public readonly int Weight;

        /// <summary>
        /// Ref测试
        /// </summary>
        public readonly int AI;

        /// <summary>
        /// Ref测试
        /// </summary>
        public AIConfig AIConfig => AIConfigCategory.Instance.GetOrDefault(AI);

        /// <summary>
        /// 数值
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<NumericType, long> Numeric;

        public const int __ID__ = -568528378;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Type:" + Type + ","
            + "Name:" + Name + ","
            + "Position:" + Position + ","
            + "Height:" + Height + ","
            + "Weight:" + Weight + ","
            + "AI:" + AI + ","
            + "Numeric:" + Luban.StringUtil.CollectionToString(Numeric) + ","
            + "}";
        }

        partial void PostInit();
    }
}
